ARG DOCKER_CLI_IMAGE=docker:29.3.0-cli
FROM ${DOCKER_CLI_IMAGE} AS docker-cli

FROM python:3.12.11-slim-bookworm

COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker
COPY broker.py /opt/anythingllm-sandbox/broker.py

ENV HOME=/tmp

ENTRYPOINT ["python3", "/opt/anythingllm-sandbox/broker.py"]
